### ISSUE TITLE
iPhone x

### ISSUE THREAD

**Issue by jackpaster** [michalziman/mz-location-picker#1]
@michalziman Can you update this project to fit with iPhone x, its a great framework but I can't use it if its not compatible. the views are covered by the notch in the status bar in curves down at the bottom. Please look into it and have it updated as soon as possible.

**Comment by michalziman** [comment]
Hey Jack!

I already had some hot fix. Thanks for reminding to publish it. I even improved it a little, to also avoid overlapping at the bottom of iPhone X screen.

Thanks for using MZLocationPicker.

Cheers!
Michal
